# fly.toml app configuration file generated for react-wasm-holy-violet-8070 on 2025-01-06T16:45:29+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-wasm-holy-violet-8070'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
